name = "PolyhedralOverapproximation"
uuid = "a17d2d74-4023-4ab1-aa92-b9763940ddd7"
authors = ["kylebrown <kylejbrown17@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
